### ISSUE TITLE
Lint on the fly does not work

### ISSUE THREAD

**Issue by LebedevAntony** [AtomLinter/linter-haml#10]
Hello!

I've just installed linter (1.3.1) plugin and linter-haml (0.4.0) plugin into Atom 1.0.4. Haven't added any additional settings but linting on the fly doesn't work.
Since lint-ing works via console (executing haml-lint gem) I guess there is no problem with my Ruby.
Also it doesn't look like a problem in Linter plugin because .scss lint-ing works too.

P.S. running it under windows 8.1 and ruby 2.0

**Comment by steelbrain** [comment]
This linter using the API that's been removed from the latest version, you could wait for the package maintainer to upgrade it or downgrade your `linter` using `apm install linter@1.2.4`

**Comment by LebedevAntony** [comment]
Ok, it's clear now. Thank you.
