### ISSUE TITLE
parser warning breaks linter-haml

### ISSUE THREAD

**Issue by goranovs** [AtomLinter/linter-haml#117]
For some reason linter-haml is not working when this warning is there. It is a warning not an error.
`haml-lint` its working in iTerm (same warning there).

<img width="485" alt="screen shot 2016-10-26 at 6 20 18 pm" src="https://cloud.githubusercontent.com/assets/2466340/19732363/39c1b220-9ba9-11e6-8720-e85ba1b478b1.png">

```
Error: warning: parser/current is loading parser/ruby22, which recognizes warning: 2.2.5-compliant syntax, but you are running 2.2.2. warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Error: warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.5-compliant syntax, but you are running 2.2.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
    at ChildProcess.<anonymous> (/Users/samuilgoranov/.atom/packages/linter-haml/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by unmultimedio** [comment]
Same here, this appears everytime I hit save on a `*.haml` file.

<img width="457" alt="screen shot 2016-11-30 at 12 24 45" src="https://cloud.githubusercontent.com/assets/4431392/20763466/23192a0c-b6f8-11e6-9b46-848f67712513.png">


But when in terminal:

```
» ruby -v                              [12:25:00]
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
```

I had to disable temporary.

**Comment by Arcanemagus** [comment]
@unmultimedio it sounds like your Atom environment is different from your shell, you may need to manually specify the path to `haml-lint`.

@Zaifor interesting, looks like putting a try/catch block around [here](https://github.com/AtomLinter/linter-haml/blob/2a7e3b7614c471d80b3ac334ffdbbbb15d2a4d90/lib/main.js#L65) and translating that into a linter message (somewhat like what was done [here](https://github.com/AtomLinter/linter-flake8/pull/277)) is probably the right way to go.

If you want to put up a PR implementing that I'd be happy to review it, as I don't use this linter myself though it will be a while before I can get to it. Unless you want to tackle it @jschroeder9000?

**Comment by lukecartledge** [comment]
Similar issue for myself.

![screen shot 2017-02-07 at 15 40 19](https://cloud.githubusercontent.com/assets/12953472/22698190/cc00c2c2-ed4b-11e6-9353-6d49be7ffda0.png)

Is there a suggested fix other than disabling?

**Comment by Arcanemagus** [comment]
@lukecartledge The fix is to read the warning, then update your Ruby install like it's telling you to do 😛.

**Comment by lukecartledge** [comment]
@Arcanemagus Unfortunately, this is part of a project with a specified (2.2.3) Ruby version. I had already tried installing that version as was suggested in the warning.

**Comment by sentience** [comment]
I resolved this by altering the binstub generated by Bundler ([see `bundle binstubs`](http://bundler.io/v1.10/bundle_binstubs.html)) for haml-lint to run Ruby with a `-W0` argument to suppress warnings:

```
#!/usr/bin/env ruby -W0
#
# This file was generated by Bundler.
#
# The application 'haml-lint' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'

load Gem.bin_path('haml_lint', 'haml-lint')
```

Then I pointed linter-haml at this binstub rather than at the haml-lint binary.

**Comment by westoque** [comment]
@sentience that did it for me. but we do need a better solution. if i have time this weekend i'll probably dive into the code and fix.
