### ISSUE TITLE
Set custom rubocop config location

### ISSUE THREAD

**Issue by BM5k** [AtomLinter/linter-haml#118]
I'm trying to enforce two different configurations for a single cop (one for haml, the other for ruby).

It seems like the only way to do this is to specify a separate `rubocop.yml` for `haml-lint`, which works via the `HAML_LINT_RUBOCOP_CONF` environment variable.

How can I pass this env var from linter-haml?

**Comment by Arcanemagus** [comment]
Atom's environment is inherited from the place where it is launched, you _should_ be able to just launch Atom from a CLI where that is defined with `atom .` and I think it will enhance the environment in that new window for you, if that doesn't work then close _all_ instances of Atom, and then launch from the CLI and it should inherit that.
