### ISSUE TITLE
Error: spawn haml-lint ENOENT

### ISSUE THREAD

**Issue by alexwasik** [AtomLinter/linter-haml#119]
## Issue
Error: spawn haml-lint ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
## Details
Atom v. 1.11.2
OSX Yosemite 10.10.5

**Comment by webzorg** [comment]
same problem. RVM doesn't create haml-lint executable wrapper in .rvm/wrappers/rubyVersion/haml-lint. I would love to see this resolved.

**Comment by Arcanemagus** [comment]
@alexwasik Do you have the `haml_lint` (yes, `_`) gem installed?

@webzorg We have absolutely nothing to do with RVM (or `haml-lint`), you'll need to file an issue elsewhere to get that fixed.

**Comment by alexwasik** [comment]
@Arcanemagus I do not have that gem installed in my project.

**Comment by webzorg** [comment]
I launch atom normally, not from terminal thus it doesn't get the PATH variables. In order for it to know where haml-lint executable is located, I have to manually input its path. While I tried all the options, it throws more and more errors. `Error: spawn haml-lint ENOENT` is one of them.

**Comment by webzorg** [comment]
alex instal haml-lint gem and see if it works, if it doesn't you need to manually input the gem executable path in the extension settings page.

**Comment by joshroman** [comment]
Just ran into same issue (Atom 1.11.2 on Sierra) & fixed with advice from @webzorg :
`gem install haml-lint`
`which haml-lint`
and then copying path into the Executable Path in the Linter Haml package settings.

**Comment by webzorg** [comment]
That doesn't help me though :D But glad you fixed x)

**Comment by alexwasik** [comment]
installing the gem solved the error issue. Please consider my issue closed.
🍻

**Comment by Arcanemagus** [comment]
Thanks for reporting back @alexwasik!

@webzorg if you are still having problems please file a new issue.
