### ISSUE TITLE
Rubocop project config is not using by linter-haml

### ISSUE THREAD

**Issue by mico** [AtomLinter/linter-haml#16]
I have .rubocop.yml in root of my project, but it's not using in linter-haml.
I've defined line length, but it's not working.

**Comment by averaart** [comment]
+1

**Comment by jschroeder9000** [comment]
The `.rubocop.yml` file should be used.  Specifically with regard to line length, I wonder if there could be some confusion that [rubocop has a line length setting](https://github.com/bbatsov/rubocop/blob/1e64d8b1334f09c091b2544d1c50baac385bffaf/config/default.yml#L965), but [so does haml-lint](https://github.com/brigade/haml-lint/blob/dd74006215d69a4efa61606c7eb5dc884d322f29/config/default.yml#L43).

More information would be needed to debug this.  A sample project that can reproduce the issue would probably be an ideal starting point.

**Comment by Arcanemagus** [comment]
I'm marking #113 as fixing this, since it is removing the temporary file copying, if it is still broken after the v2.0.0 release please file a new issue.
