### ISSUE TITLE
Not work with ruby 2.5.4+

### ISSUE THREAD

**Issue by denvic69** [AtomLinter/linter-haml#160]
Hello. haml-lint work from command line.
But atom not show lint warning
`ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
haml-lint -v
haml-lint 0.28.0
haml-lint .
log_view.html.haml:18 [W] LineLength: Line is too long. [172/80]

1 file inspected, 1 lint detected
dvm@massahouse:~/RoR/tham$ atom log_view.html.haml 
`
![Снимок экрана из 2019-03-22 18-00-57](https://user-images.githubusercontent.com/44612437/54832043-816db200-4ccc-11e9-91ca-08867925dac3.png)

**Comment by Wirwing** [comment]
@denvic69, I am having the same issue, were you able to fix it?

**Comment by Arcanemagus** [comment]
Please file your own issue so it can get diagnosed without spamming in here. Note that actually including the error message (which wasn't done here) would be the first step to tracking down what is wrong.
