### ISSUE TITLE
Failed to spawn command haml-lint. Make sure haml-lint is installed and on your PATH

### ISSUE THREAD

**Issue by aronlmin** [AtomLinter/linter-haml#60]
im getting the big red error in the top right hand corner with 

"Failed to spawn command haml-lint. Make sure haml-lint is installed and on your PATH"

the command window opens at the bottom of my screen like chrome's dev tool and it has 368 errors in it too....

all has worked fine until i installed this package :(

**Comment by Arcanemagus** [comment]
Do you have `haml-lint` installed?

**Comment by aronlmin** [comment]
currently i have it disabled but yes

**Comment by Arcanemagus** [comment]
Not `linter-haml`, but the actual `haml-lint` program. Meaning if you open up a CLI and run `haml-lint` do you get something?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

**Comment by whlsxl** [comment]
solve this by install `gem install haml-lint`

**Comment by cparker-ajla** [comment]
Posting this in case it might help someone else.  In my case, I forgot I had installed the gem using bundler.   What fixed it for me was creating another alias in bash:
  `alias haml-lint='bundle exec haml-lint'`

After a reboot, no more errors,
