### ISSUE TITLE
RuboCop Errors » Unexpected tokens

### ISSUE THREAD

**Issue by jufemaiz** [AtomLinter/linter-haml#99]
Hi guys, I'm finding an issue with my haml-linting using linter-haml in atom.

It seems like the rubocop implementation isn't realising that the file is a HAML file.

<img width="461" alt="screen shot 2016-07-19 at 1 17 36 pm" src="https://cloud.githubusercontent.com/assets/16481/16937544/39b6a1d0-4db3-11e6-9fe9-ce34525bfe1f.png">

This is what I see at the bottom of my *.html.haml pages.

If I run from command line "haml-lint app/views" there's no reference to these errors.

Thoughts?

**Comment by Arcanemagus** [comment]
Those errors are coming from a linter that identifies as `RuboCop`, since [the one](https://github.com/AtomLinter/linter-rubocop) maintained in this organization identifies as `rubocop`, I'm not sure what linter that is. In any case the problem lies with that linter, not `linter-haml`.

**Comment by jufemaiz** [comment]
@Arcanemagus I'm scratching my head too!

Disabling https://atom.io/packages/linter-rubocop removes the problem.
Enabling https://atom.io/packages/linter-rubocop comes up as "RuboCop" in atom for me.

**Comment by jufemaiz** [comment]
Actually @Arcanemagus can you confirm the lowercase v camelcase?

https://github.com/AtomLinter/linter-rubocop/blob/master/lib/index.coffee#L41

**Comment by Arcanemagus** [comment]
Ha, whoops, you are absolutely correct that it is `RuboCop`, my eyes skipped down to L57 there 😞.

Can you file an issue over there with the scopes you see listed when you run `Editor: Log Cursor Scopes`?

**Comment by jufemaiz** [comment]
Ah crap, now nothing's working :(

**Comment by jufemaiz** [comment]
Ok. Rebuilt my packages.

```
atom-beautify
language-haml
linter
linter-coffeelint
linter-haml
linter-rubocop
linter-scss-lint
```

Using rails. .rubocop.yml exists

```.rubocop.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - lib/intern2016/legacy.rb
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  Max: 160
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
```

No .haml-lint.yml configuration file at this stage.

AND WE'RE BACK!

Thanks for your time :) Bizarre. Sometimes you've just got to turn it off + on again (aka fresh build)

**Comment by jufemaiz** [comment]
And back to the same problem :(

**Comment by Arcanemagus** [comment]
Like I said, please [file an issue](https://github.com/AtomLinter/linter-rubocop/issues/new) over there with the output of running `Editor: Log Cursor Scopes` from the command palette when you have a Haml file open.

**Comment by jufemaiz** [comment]
Thanks @Arcanemagus. Will do.
